# Generated by Django 3.0.2 on 2020-04-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='first_name',
            field=models.CharField(default='null', max_length=20),
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='last_name',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
